apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
spec:
  replicas: 1   # hostPort → only one pod per node
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: neerajreddy22/swe645-assignment2-neerajreddykarnati:v1
        ports:
        - containerPort: 80
          hostPort: 30080
