apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
  labels:
    app: student-survey
spec:
  replicas: 3   # requirement for resiliency/scalability
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: neerajreddy22/swe645-assignment2-neerajreddykarnati:latest
        ports:
        - containerPort: 80
