apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-sample-deployment
  labels:
    app: swe645-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-sample
  template:
    metadata:
      labels:
        app: swe645-sample
    spec:
      containers:
        - name: swe645-sample
          image: YOUR_REGISTRY/swe645-sample:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
